Deduplicate finalPackages
After moving code around, I think I accidentally duplicated the
implementation of finalPackages, which has lead to the problem:

> It looks like `readonly` has no effect, because I can still set
> `finalPackages.foo = ./.;` (even `finalPackages = ./.;`) in
> `test/flake.nix`?

With this fix, it reports:

    error: The option `perSystem.x86_64-linux.haskellProjects.default.finalPackages' is read-only, but it's set multiple times. Definition values:
           - In `/nix/store/n0vj61wy18j094y6gpzjvq5g0w63d637-source/flake.nix, via option perSystem'
           - In `/nix/store/yp9drmdqfgq74c5ap90cq9jqis4yiw41-source/haskell-project.nix'

I suspect that it happened when I did a

    git checkout <rev> haskell-project.nix

at some point, with the goal of easily minimizing the diff. That
was probably inaccurate.